[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 0
y = 0

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"   

[colors.primary]
background = "#222436"
foreground = "#c8d3f5"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.selection]
background = "#28344a"
text = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

