[mgr]
show_hidden  = false
linemode     = "size_and_mtime"
show_symlink = true

[opener]
edit = [
    { run = '$EDITOR %s', block = true, for = "unix" },
]

[plugin]
prepend_keymap = [
    { on = ["Z"], run = "plugin zoxide", desc = "Jump with zoxide" }
]
